services:
  Lanius\Jobman\:
    resource: '../Classes/*'
    autowire: true
    autoconfigure: true

  Lanius\Jobman\PageTitle\TitleTag:
    public: true       
    autowire: true
    autoconfigure: true
    tags:
      - { name: 'core.pageTitleProvider', identifier: 'jobman' }